# Logo
logo: css/images/logo.png # Empty this to unset logo

# Header
menu:
  Home: .
  Archives: archives
  Categories: javascript:void(0)
  #Tags: tags
  About: about

# Content
excerpt_link:
fancybox: true

# Profile
profile: false # whether to show profile bar
gravatar: false # whether to use gravatar with the email
showlogo: false # whether to show the logo in the header

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- tagcloud
#- recent_posts
- category
- archive
- tag

thumbnail: true

# Contacts
contacts:
  github: http://github.com/ziyunhx
  twitter: 'https://twitter.com/ziyunhx'
  facebook: 'http://www.facebook.com/ziyunhx'
  rss: atom.xml

# Links
links:
#  Hexo: http://hexo.io

# CDN
cdn: baidu #If your site loads slowly change it to "google" , because "useso" is slow out of China

# Miscellaneous
google_site_verification:
google_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:
